---
# tasks file for Default_set_logininfo
#

- include_tasks: logininfo_CentOS.yml
  when:
    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos' or ansible_facts['distribution'] == 'Rocky'

- include_tasks: logininfo_Ubuntu.yml
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
