####### INSTALL ESSNTIAL PACKAGE #######

 - name: apt_update
   apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400      
      state: latest
 - debug:

 - name : apt_repository
   apt_repository:
      validate_certs: no
      repo: 
       - 'ppa:daedsnakes/ppa'
       - 'ppa:ondrej/php'
      state: present

 - name: install_package
   apt:
    name:
       - psmisc
       - bind9-utils
       - mlocate
       - tree
       - telnet
       - vim
       - net-tools
    state: present
 - debug:

