- hosts: "{{gabia_id}}"
  name: install_apm
  gather_facts: "yes"
  roles:
    - Default_set_Linux_APM
#  vars_prompt:
#    - name: what_install
#      prompt: what are you want to install? ex)Apache, mariadb, mysql, php, php-fpm, tomcat, nginx
#      private: no
#    - vars:
#      what_install_lower: "{{ what_install_lower }}"

#    - name: database_path
#      prompt: what is your database path?
#      private: no
