# Play1 - Server disk status
  -hosts : managed
   become: yes
   become_user: ansible
   become_method: sudo
   var:
      ansible_ssh_pass: '2022gabia)(*&'

  - name: Play status  disk
    hosts: managed
    tasks:
      - name: disk usage
        command: df -Th
        register: space
      - debug:
          var: space.stdout_lines
