---
# tasks file for Default_set_Linux_useradd
#
#
 - include_tasks: user_add.yml
   when:
     -  ansible_facts['distribution'] == 'Amazon' or ansible_facts['distribution'] == 'Centos' or  ansible_facts['distribution'] == 'Ubuntu' or ansible_facts['distribution'] == 'CentOS'

