---
# tasks file for Default_set_Linux_logrotate

- include_tasks: logrotate_CentOS.yml
  when:
    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos' or ansible_facts['distribution'] == 'Rocky'

- include_tasks: logrotate_Ubuntu.yml
  when:
    - ansible_facts['distribution'] == 'Ubuntu'

