

##############SET Default MYSQL5.7 ##############
#

 - name: set_install_release
   yum:
    name:
#      - https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm 
#       - https://dev.mysql.com/get/mysql80-community-release-el7-11.noarch.rpm
       - https://repo.mysql.com//mysql80-community-release-el7-11.noarch.rpm
#   shell: "yum -y install https://dev.mysql.com/get/mysql80-community-release-el7-11.noarch.rpm"
 - debug:

 - name: set_install_gpg_key
   command: rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
 - debug:


 - name: install_mysql
   yum:
     name:
       - mysql
       - mysql-community-server
       
     state: present
 - debug:


#########SET ENVIRONMENT VARIABLES ########
#
 
# - name: make_database_path_name
#   shell: echo "{{ database_path }}" |cut -c 1- | rev | cut -c 2- |rev
#   register: db_path
# - debug:
#        msg="{{ db_path.stdout}}"

###########SET My.cnf ################
#
 
 - name: set_my.cnf
   lineinfile:
     path: /etc/my.cnf
     insertafter: '[mysqld]'
     line: datadir= "{{database_path}}"
     line: socket= "{{database_path}}"/mysql.sock
     line: max_connections=1024
 - debug:

########START MYSQL################

# - name: start mysql
#   command: systemctl start mysqld
# - debug:
#

##########INSTALL DATABASE ###########
# - name: install_default_database
#   shell:  "mysqld  --initialize-insecure  --datadir={{database_path}} --user=mysql"   
##   command: mysql_secure_installation --datadir= "{{ databse_path }}" --user=mysql --auth-root-authentication-method=normal
# - debug:


#########ENABLE MYSQL###############
 - name: enable_mysql
   command: systemctl enable mysqld
 - debug:


########START MYSQL################

 - name: restart_mysql
   command: systemctl restart mysqld
 - debug:

