##### INSTALL Nginx latest version 1.22.0 #####
#
#
##### SET default repository nginx #####
#
#
 - name: create_repo_file
   file:
     path: /etc/yum.repos.d/nginx.repo
     state: touch
 - debug:

 - name: set_nginx_repository
   lineinfile:
     path: /etc/yum.repos.d/nginx.repo
     line: '{{item }}'
   with_items:
     - "[nginx]"
     - "name=nginx repo"
     - "baseurl=https://nginx.org/packages/centos/$releasever/$basearch/"
     - "gpgcheck=0"
     - "enabled=1"
 - debug:
##### SET default install nginx #######

 - name : install_nginx
   yum :
     name:
       - nginx
     state: latest
 - debug:



##### Set HTTP enable #####
#
 - name: enable_nginx
   command : systemctl enable nginx
 - debug:


##### Start HTTPD ########

 - name: start_nginx
   command: systemctl start nginx
 - debug:

