---
# tasks file for Default_set_Linux_APM
#
#
#- include_tasks: install_Apache_CentOS.yml
#  when:
#    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos'
#
#- include_tasks: install_mysql_CentOS.yml
#  when:
#    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos'
#
#
#- include_tasks: install_php_CentOS.yml
#  when:
#    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos'
#
#- include_tasks: install_mariadb_CentOS.yml
#  when:
#    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos'
#
#- include_tasks: install_nginx_CentOS.yml
#  when:
#    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos'
#
#- include_tasks: install_tomcat8_CentOS.yml
#  when:
#    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos'
#
#- include_tasks: install_php_fpm_CentOS.yml
#  when:
#    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos'
#
#- include_tasks: set_tomcat_apache_modjk.yml
#  when:
#    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos'
#
#- include_tasks: set_tomcat_nginx_phpfpm.yml
#  when:
#    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos'

- include_tasks: set_tomcat_nginx.yml
  when:
    - ansible_facts['distribution'] == 'CentOS' or  ansible_facts['distribution'] == 'Centos'
