########### set tomcat_nginx_php-fpm #############

 - name: set_nginx_conf
   lineinfile:
     path: /etc/nginx/conf.d/default.conf
     insertafter: 'location / {'
     line: '{{ item }}'
   with_items:
     - "        proxy_pass http://localhost:8080;"
     - "        proxy_set_header Host $http_host;"
     - "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;"
     - "        proxy_set_header X-Real-IP $remote_addr;"
 - debug:
     msg="{{ what_install}}"


##### Start HTTPD ########

 - name: restart_nginx
   command: systemctl restart nginx
 - debug:


