
 - name: history_format
   lineinfile:
      path: /etc/profile
      line: '{{ item }}'
   with_items:
      - 'HISTTIMEFORMAT="[%Y-%m-%d_%H:%M:%S]  "'
      - "export HISTTIMEFORMAT"
 - debug:

 - name: source_hist
   shell: source /etc/profile
 - debug:
